import type { Event } from "@/types/event"
import type { Organizer } from "@/types/organizer"
import type { Post } from "@/types/post"

export const DUMMY_ORGANIZERS: Organizer[] = [
  {
    id: "org1",
    name: "Downtown Events Co.",
    username: "downtownevents",
    avatar: "/placeholder.svg?height=100&width=100",
    banner: "/placeholder.svg?height=300&width=800",
    bio: "We organize the best events in the downtown area. From music festivals to art exhibitions, we've got you covered.",
    email: "contact@downtownevents.com",
    website: "https://downtownevents.com",
    location: "Downtown, Cityville",
    followers: 1250,
    eventCount: 48,
    verified: true,
  },
  {
    id: "org2",
    name: "Community Arts Center",
    username: "artscenter",
    avatar: "/placeholder.svg?height=100&width=100",
    banner: "/placeholder.svg?height=300&width=800",
    bio: "Promoting local arts and culture through exhibitions, workshops, and community events.",
    email: "info@artscenter.org",
    website: "https://artscenter.org",
    location: "Midtown, Cityville",
    followers: 875,
    eventCount: 32,
    verified: true,
  },
  {
    id: "org3",
    name: "Tech Meetups",
    username: "techmeetups",
    avatar: "/placeholder.svg?height=100&width=100",
    banner: "/placeholder.svg?height=300&width=800",
    bio: "Connecting tech enthusiasts through regular meetups, workshops, and networking events.",
    email: "hello@techmeetups.com",
    website: "https://techmeetups.com",
    location: "Innovation District, Cityville",
    followers: 950,
    eventCount: 24,
    verified: false,
  },
  {
    id: "org4",
    name: "Fitness Collective",
    username: "fitnesscollective",
    avatar: "/placeholder.svg?height=100&width=100",
    banner: "/placeholder.svg?height=300&width=800",
    bio: "Group fitness events, outdoor activities, and wellness workshops for all fitness levels.",
    email: "info@fitnesscollective.com",
    website: "https://fitnesscollective.com",
    location: "Parkside, Cityville",
    followers: 720,
    eventCount: 36,
    verified: false,
  },
]

export const DUMMY_EVENTS: Event[] = [
  {
    id: "evt1",
    title: "Music Festival",
    description: "Join us for a day of live music and fun in the park.",
    date: "2023-10-15",
    time: "12:00 PM - 6:00 PM",
    location: "Central Park, Cityville",
    image: "/placeholder.svg?height=300&width=500",
    category: "Music",
    tags: ["music", "festival", "live", "outdoor"],
    attendees: 250,
    month: "Oct",
    day: "15",
    featured: true,
    ticketPrice: 25,
    ticketAvailability: "Limited tickets available",
    organizer: {
      id: "org1",
      name: "Downtown Events Co.",
      avatar: "/placeholder.svg?height=100&width=100",
    },
    comments: [
      {
        id: "cmt1",
        userId: "usr1",
        text: "Can't wait to see the lineup!",
      },
      {
        id: "cmt2",
        userId: "usr2",
        text: "Great event, looking forward to it!",
      },
    ],
  },
  {
    id: "evt2",
    title: "Art Exhibition",
    description: "Explore local talent at our annual art exhibition.",
    date: "2023-11-01",
    time: "10:00 AM - 4:00 PM",
    location: "Community Arts Center, Midtown",
    image: "/placeholder.svg?height=300&width=500",
    category: "Arts",
    tags: ["art", "exhibition", "culture", "local"],
    attendees: 150,
    month: "Nov",
    day: "01",
    featured: false,
    ticketPrice: 10,
    ticketAvailability: "Tickets available",
    organizer: {
      id: "org2",
      name: "Community Arts Center",
      avatar: "/placeholder.svg?height=100&width=100",
    },
    comments: [
      {
        id: "cmt3",
        userId: "usr3",
        text: "Beautiful artwork!",
      },
      {
        id: "cmt4",
        userId: "usr4",
        text: "Definitely going to check it out.",
      },
    ],
  },
  {
    id: "evt3",
    title: "Tech Meetup",
    description: "Discuss the latest tech trends with fellow enthusiasts.",
    date: "2023-10-20",
    time: "7:00 PM - 9:00 PM",
    location: "Tech Hub, Innovation District",
    image: "/placeholder.svg?height=300&width=500",
    category: "Technology",
    tags: ["tech", "networking", "innovation", "meetup"],
    attendees: 100,
    month: "Oct",
    day: "20",
    featured: false,
    ticketPrice: 0,
    ticketAvailability: "Free event",
    organizer: {
      id: "org3",
      name: "Tech Meetups",
      avatar: "/placeholder.svg?height=100&width=100",
    },
    comments: [
      {
        id: "cmt5",
        userId: "usr5",
        text: "Excited for the meetup!",
      },
      {
        id: "cmt6",
        userId: "usr6",
        text: "Looking forward to networking.",
      },
    ],
  },
  {
    id: "evt4",
    title: "Fitness Workshop",
    description: "Learn new fitness routines and stay healthy.",
    date: "2023-10-25",
    time: "9:00 AM - 11:00 AM",
    location: "Fitness Park, Parkside",
    image: "/placeholder.svg?height=300&width=500",
    category: "Health",
    tags: ["fitness", "health", "workshop", "wellness"],
    attendees: 80,
    month: "Oct",
    day: "25",
    featured: false,
    ticketPrice: 15,
    ticketAvailability: "Tickets available",
    organizer: {
      id: "org4",
      name: "Fitness Collective",
      avatar: "/placeholder.svg?height=100&width=100",
    },
    comments: [
      {
        id: "cmt7",
        userId: "usr7",
        text: "Great for beginners!",
      },
      {
        id: "cmt8",
        userId: "usr8",
        text: "Looking forward to trying out new exercises.",
      },
    ],
  },
]

export const DUMMY_POSTS: Post[] = [
  {
    id: "post1",
    author: DUMMY_ORGANIZERS[0],
    content: "We're excited to announce our upcoming Music Festival! Get your tickets early for special discounts.",
    image: "/placeholder.svg?height=400&width=600",
    createdAt: "2023-09-25T14:30:00Z",
    likes: 124,
    comments: 32,
    hashtags: ["music", "festival", "downtown"],
    event: {
      id: "evt1",
      title: "Music Festival",
      date: "October 15, 2023",
      location: "Central Park, Cityville",
      image: "/placeholder.svg?height=200&width=300",
    },
  },
  {
    id: "post2",
    author: DUMMY_ORGANIZERS[1],
    content: "Our art exhibition is just around the corner! We'll be featuring works from over 30 local artists.",
    image: "/placeholder.svg?height=400&width=600",
    createdAt: "2023-09-28T10:15:00Z",
    likes: 87,
    comments: 18,
    hashtags: ["art", "exhibition", "local"],
    event: {
      id: "evt2",
      title: "Art Exhibition",
      date: "November 1, 2023",
      location: "Community Arts Center, Midtown",
      image: "/placeholder.svg?height=200&width=300",
    },
  },
  {
    id: "post3",
    author: DUMMY_ORGANIZERS[2],
    content: "Looking forward to discussing the latest in AI and machine learning at our next tech meetup!",
    image: "/placeholder.svg?height=400&width=600",
    createdAt: "2023-09-30T16:45:00Z",
    likes: 56,
    comments: 14,
    hashtags: ["tech", "AI", "machinelearning"],
    event: {
      id: "evt3",
      title: "Tech Meetup",
      date: "October 20, 2023",
      location: "Tech Hub, Innovation District",
      image: "/placeholder.svg?height=200&width=300",
    },
  },
  {
    id: "post4",
    author: DUMMY_ORGANIZERS[3],
    content: "Join us for a morning of fitness and wellness. All fitness levels welcome!",
    image: "/placeholder.svg?height=400&width=600",
    createdAt: "2023-10-01T09:20:00Z",
    likes: 42,
    comments: 8,
    hashtags: ["fitness", "wellness", "health"],
    event: {
      id: "evt4",
      title: "Fitness Workshop",
      date: "October 25, 2023",
      location: "Fitness Park, Parkside",
      image: "/placeholder.svg?height=200&width=300",
    },
  },
  {
    id: "post5",
    author: DUMMY_ORGANIZERS[0],
    content: "Thank you to everyone who attended our last event! Here are some highlights from the day.",
    image: "/placeholder.svg?height=400&width=600",
    createdAt: "2023-10-02T11:30:00Z",
    likes: 98,
    comments: 22,
    hashtags: ["events", "highlights", "thankyou"],
  },
  {
    id: "post6",
    author: DUMMY_ORGANIZERS[1],
    content: "We're looking for volunteers for our upcoming community art project. DM us if you're interested!",
    createdAt: "2023-10-03T13:15:00Z",
    likes: 34,
    comments: 16,
    hashtags: ["volunteers", "community", "art"],
  },
]
